const express = require('express')
const router = express.Router()
const auth = require('../middlewares/check-auth')
const RoleController = require('../controllers/role')
router.get('/', [auth.veify_auth],RoleController.getRoles)
router.post('/', [auth.veify_auth], RoleController.storeRole)
router.get('/:id', [auth.veify_auth], RoleController.getRole)
router.put('/:id', [auth.veify_auth], RoleController.updateRole)
router.delete('/:id', [auth.veify_auth], RoleController.removeRole)
module.exports = router