const express = require('express')
const router = express.Router()
const auth = require('../middlewares/check-auth')
const StatusController = require('../controllers/status')
router.get('/', [auth.veify_auth], StatusController.getStatuses)
router.get('/:id', [auth.veify_auth], StatusController.getStatus)
router.post('/', [auth.veify_auth], StatusController.storeStatus)
router.put('/:id', [auth.veify_auth], StatusController.updateStatus)
router.delete('/:id', [auth.veify_auth], StatusController.removeStatus)
module.exports = router