const express = require('express')
const router = express.Router()
const auth = require('../middlewares/check-auth')
const TicketController = require('../controllers/ticket')
router.get('/', [auth.veify_auth], TicketController.getTickets)
router.post('/', [auth.veify_auth], TicketController.storeTicket)
router.get('/:id', [auth.veify_auth], TicketController.getTicket)
router.put('/:id', [auth.veify_auth], TicketController.updateTicket)
router.delete('/:id', [auth.veify_auth],TicketController.removeTicket)
module.exports = router