const express = require('express')
const router = express.Router()
const auth = require('../middlewares/check-auth')
const UserController = require('../controllers/user')
router.get('/', [auth.veify_auth], UserController.getUsers)
router.post('/', [auth.veify_auth],UserController.storeUser)
router.post('/login', UserController.login)
router.get('/:id', [auth.veify_auth],UserController.getUser)
router.put(':/id', [auth.veify_auth],UserController.updateUser)
router.delete('/:id', [auth.veify_auth],UserController.removeUser)
module.exports= router